issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
  - id: portcullis-gate
    secret: portcullis-gate-secret
    name: Portcullis Gate
    redirectURIs:
      - http://localhost:7777/auth/callback

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    hash: "$2y$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"  # bcrypt of "password"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

oauth2:
  skipApprovalScreen: true
