issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:

  - id: portcullis-keep
    name: Portcullis Keep
    secret: portcullis-keep-secret
    trustedPeers:
      - portcullis-gate

  - id: portcullis-gate
    secret: portcullis-gate-secret
    name: Portcullis Gate
    redirectURIs:
      - http://localhost:7777/auth/callback

  - id: portcullis-guard
    secret: portcullis-guard-secret
    name: Portcullis Guard
    redirectURIs:
      - http://localhost:8444/auth/callback

enablePasswordDB: true

staticPasswords:
  - email: "developer@paclabs.net"
    hash: "$2y$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"  # bcrypt of "password"
    username: "developer"
    userID: "developer@paclabs.net"
    name: "Dana Developer"
    groups:
      - "developer"

  - email: "admin@paclabs.net"
    hash: "$2y$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"  # bcrypt of "password"
    username: "admin"
    userID: "admin@paclabs.net"
    name: "Alex Admin"
    groups:
      - "admin"
      - "developer"

  - email: "clerk@paclabs.net"
    hash: "$2y$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"  # bcrypt of "password"
    username: "clerk"
    userID: "clerk@paclabs.net"
    name: "Casey Clerk"
    groups:
      - "clerk"

oauth2:
  skipApprovalScreen: true
